# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  demands:
    - npm

variables:
  buildConfiguration: 'Release'



steps:

- task: Npm@1
  inputs:
    command: 'install'
- task: CmdLine@2
  inputs:
    script: |
      pwd
      ls -ltr
      ls -ltr ./node_modules
      ls -ltr ./node_modules/.bin
      ls -ltr ./node_modules/.bin/node-sass
      ls -ltr Tailspin.SpaceGame.Web/wwwroot
- task: CmdLine@2
  displayName: "Run node modules node-sass"
  inputs:
    script: '''./node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'''
- task: gulp@0
  inputs:
    gulpFile: 'gulpfile.js'

    targets: 
    gulpjs: 'node_modules/gulp/bin/gulp.js'
    enableCodeCoverage: false

- task: CmdLine@2
  inputs:
    script: 'echo $(Build.BuildId),$(Build.DefinitionName	),$(Build.BuildNumber)> "buildinfo.txt"'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--no-restore --configuration Release'